### ISSUE TITLE
Issue while installing scrapy-deltafetch

### ISSUE THREAD

**Issue by hendisantika** [scrapy-plugins/scrapy-deltafetch#15]
Hi, 
I want to add scrapy-deltafetch on my scrapy project. Then
I have an issue while installing scrapy-deltafetch.

My Python Version in Python 2.7.12

Here're the logs from terminal : 

```Collecting scrapy-deltafetch
  Using cached scrapy_deltafetch-1.2.0-py2.py3-none-any.whl
Requirement already satisfied: Scrapy>=1.0 in /home/hendisantika/Documents/python/ENV/lib/python2.7/site-packages (from scrapy-deltafetch)
Collecting bsddb3 (from scrapy-deltafetch)
  Using cached bsddb3-6.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Jzfv8A/bsddb3/
```

Do you have any solution for my case?

Thanks.

**Comment by redapple** [comment]
Hello @hendisantika ,
what system are you installing scrapy-deltafetch on?
If it's Ubuntu/Debian, you'll have to install `libdb-dev` (something like `sudo apt-get install libdb-dev`)
as outlined in the [Requirements section](https://github.com/scrapy-plugins/scrapy-deltafetch#requirements).

**Comment by hendisantika** [comment]
Oh God,
I am very sorry.
I miss that line.
I am using Ubuntu/Debian.
OK. Solved.

:+1:  :100: 

Thanks

**Comment by redapple** [comment]
Hey, don't be sorry, if you missed it it's probably because it's not visible enough :)
