### ISSUE TITLE
This plugin not working in my project somehow

### ISSUE THREAD

**Issue by Big2Cat** [scrapy-plugins/scrapy-deltafetch#20]
# System is Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)
`(Spider_py2) kong@ubuntu:~$ python -V`
`Python 2.7.12`
# I have installed Berkeley DB via:
`cd /usr/local/src`
`wget http://download.oracle.com/berkeley-db/db-4.7.25.NC.tar.gz`
`tar zxvf db-4.7.25.NC.tar.gz `
`cd build_unix`
`../dist/configure`
`make`
`make install`

# Installed bsddb3 scrapy-deltafetch scrapy-magicfields via:
`pip install bsddb3`
`pip install scrapy-deltafetch`
`pip install scrapy-magicfields`

# And now:
    (Spider_py2) kong@ubuntu:~$ pip search scrapy
    scrapy-deltafetch (1.2.1)                      - Scrapy middleware to ignore previously crawled pages
        INSTALLED: 1.2.1 (latest)
    scrapy-magicfields (1.1.0)                     - Scrapy middleware to add extra "magic" fields to items
        INSTALLED: 1.1.0 (latest)
    Scrapy (1.4.0)                                 - A high-level Web Crawling and Web Scraping framework
        INSTALLED: 1.1.0
        LATEST:    1.4.0

# The code  in setting.py:
    SPIDER_MIDDLEWARES = {     
        'scrapy_deltafetch.DeltaFetch':50,
        'scrapy_magicfields.MagicFieldsMiddleware':51,
    }
    DELTAFETCH_ENABLE = True
    MAGICFIELDS_ENABLE = True
    MAGIC_FIELDS = { 
        "crawl_time": "$time",
    }
# INFO when i ran and stoped the spider:
# ran:
    2017-06-02 17:33:14 [scrapy] INFO: Enabled spider middlewares:
    ['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
     'scrapy_magicfields.MagicFieldsMiddleware',
     'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
     'scrapy.spidermiddlewares.referer.RefererMiddleware',
     'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
     'scrapy.spidermiddlewares.depth.DepthMiddleware']
# stoped:
    2017-06-02 17:33:17 [scrapy] INFO: Dumping Scrapy stats:
    {'downloader/request_bytes': 4332,
     'downloader/request_count': 9,
     'downloader/request_method_count/GET': 9,
     'downloader/response_bytes': 32246,
     'downloader/response_count': 9,
     'downloader/response_status_count/200': 9,
     'finish_reason': 'shutdown',
     'finish_time': datetime.datetime(2017, 6, 2, 9, 33, 17, 765281),
     'item_scraped_count': 48,
     'log_count/INFO': 8,
     'request_depth_max': 3,
     'response_received_count': 9,
     'scheduler/dequeued': 9,
     'scheduler/dequeued/memory': 9,
     'scheduler/enqueued': 64,
     'scheduler/enqueued/memory': 64,
     'start_time': datetime.datetime(2017, 6, 2, 9, 33, 14, 597277)}
    2017-06-02 17:33:17 [scrapy] INFO: Spider closed (shutdown)
We can see clearly in ran INFO that the deltafetch was not on.
I've looked at the other related deltafetch questions and they did not address this issue, any assistance appreciated.

**Comment by redapple** [comment]
The setting is `DELTAFETCH_ENABLED` not `DELTAFETCH_ENABLE`. Does it change something?

**Comment by Big2Cat** [comment]
Oh no ,I am so embarrassed.
Thank you for your patience.
