### ISSUE TITLE
Installation failure on macOS

### ISSUE THREAD

**Issue by adamporad** [scrapy-plugins/scrapy-deltafetch#33]
I am unable to install `scrapy-deltafetch` on macOS using pip (running macOS Sierra version 10.12.6 on a MacBook Pro (15-inch, 2017)). 

The cause of the installation failure is that `bsddb3` fails to install because there is no local Berkeley DB installation.

```
$ pip install scrapy-deltafetch
Collecting scrapy-deltafetch
  Downloading https://files.pythonhosted.org/packages/90/81/08bd21bc3ee364845d76adef09d20d85d75851c582a2e0bb7f959d49b8e5/scrapy_deltafetch-1.2.1-py2.py3-none-any.whl
Collecting bsddb3 (from scrapy-deltafetch)
  Downloading https://files.pythonhosted.org/packages/e9/fc/ebfbd4de236b493f9ece156f816c21df0ae87ccc22604c5f9b664efef1b9/bsddb3-6.2.6.tar.gz (239kB)
    100% |████████████████████████████████| 245kB 1.9MB/s
    Complete output from command python setup.py egg_info:
    Can't find a local Berkeley DB installation.
    (suggestion: try the --berkeley-db=/path/to/bsddb option)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/pz/pmrkh2z178l5mt8kpkxhkd2h0000gp/T/pip-install-pbph5hg4/bsddb3/
```

After installing Berkeley DB using `brew install berkeley-db`, I was still not able to get `bsddb3`  installed. I didn't do any setup, configuration, etc. of Berkley DB after installing it, but gave up after that.

**Comment by asmaier** [comment]
With homebrew I was able to do it like:

    $ brew install berkeley-db@4
    $ BERKELEYDB_DIR=/usr/local/Cellar/berkeley-db\@4/4.8.30/ pip install scrapy-deltafetch

See also https://github.com/scrapy-plugins/scrapy-deltafetch/issues/23#issue-249137208 .

**Comment by jin10086** [comment]
@ryonlife 

`conda install -c conda-forge bsddb3`
and `pip install scrapy-deltafetch`

https://igaojin.me/2018/08/06/MAC-%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85-bsddb3/

**Comment by ryonlife** [comment]
After reading more closely, I can confirm https://github.com/scrapy-plugins/scrapy-deltafetch/issues/33#issuecomment-416364545 is still valid on macOS Catalina 10.15.5. My mistake was `brew install berkeley-db` rather than `brew install berkeley-db@4`. This worked for me:

```
brew install berkeley-db@4
BERKELEYDB_DIR=$(brew --prefix berkeley-db@4) pipenv install scrapy-deltafetch
```

**Comment by r0oike** [comment]
> BERKELEYDB_DIR=$(brew --prefix berkeley-db@4) pip install scrapy-deltafetch

thanks
